name: build and release and upload assets
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

  build-x86:
    runs-on: ubuntu-latest
    needs:
      - make-release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'
      - run: SN_RELEASE=fast sbt nativeLink
      - run: mv target/scala-*/poncho-out poncho_x64
      - uses: actions/upload-artifact@v3
        with:
          path: poncho_x64
          name: poncho_x64
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: poncho_x64
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
