name: build and release and upload assets
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

  build-x86:
    runs-on: ubuntu-latest
    needs:
      - make-release
    steps:
      - uses: actions/checkout@v3
      - name: install podman
        run: |
          set -x
          sudo apt-get remove -y podman docker-ce docker docker-engine docker.io containerd runc ||:
          curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_$( lsb_release -rs )/Release.key | sudo apt-key add -
          echo  "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_$( lsb_release -rs )/ /" | sudo tee /etc/apt/sources.list.d/podman.list /dev/null
          sudo apt-get update
          sudo apt-get install -y podman
          sudo apt autoremove -y
      - run: podman build . -t poncho-builder
      - run: podman run --rm -it -v "$(pwd)":'/poncho' poncho-builder
      - run: mv target/scala-*/poncho-out poncho_x64
      - uses: actions/upload-artifact@v3
        with:
          path: poncho_x64
          name: poncho_x64
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: poncho_x64
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
