name: build and release and upload assets
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

  build-arm:
    runs-on: ubuntu-latest
    needs:
      - make-release
    steps:
      - uses: actions/checkout@v3
      - uses: pguyot/arm-runner-action@v2
        with:
          base_image: raspios_lite_arm64:latest
          copy_artifact_path: poncho_arm
          commands: |
            uname -m
            sudo apt-get install -y bash git clang binutils-gold cmake make libgcc musl-dev gcc g++ libc6-compat libtool automake autoconf
            sudo apt-get install -y sbt
            git clone https://github.com/libuv/libuv && cd libuv && ./autogen.sh && ./configure && make && make install
            git clone https://github.com/bitcoin-core/secp256k1 && cd secp256k1 && ./autogen.sh && ./configure --enable-module-schnorrsig --enable-module-recovery && make && make install
            ls -thal
            cp . /poncho
            cd /poncho
            sbt clean compile
            SN_LINK=static sbt clean nativeLink
            mv target/scala-*/poncho-out poncho_arm
      - uses: actions/upload-artifact@v3
        with:
          path: poncho_arm
          name: poncho_arm
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: poncho_arm
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
