name: build and release and upload assets
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

  build-arm:
    runs-on: ubuntu-latest
    needs:
      - make-release
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v3
      - run: docker build -f Containerfile --arch arm64 . -t poncho-builder
      - run: docker run --arch arm64 -e JAVA_OPTS="-Djdk.lang.Process.launchMechanism=vfork" --rm -v "$(pwd)":'/poncho' poncho-builder
      - run: mv target/scala-*/poncho-out poncho_arm
      - uses: actions/upload-artifact@v3
        with:
          path: poncho_arm
          name: poncho_arm
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: poncho_arm
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
